# Generated by Django 6.0.5 on 2026-06-08 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_existing_tiers(apps, schema_editor):
    Profile = apps.get_model('expenses', 'Profile')
    Profile.objects.filter(subscription_tier='premium').update(subscription_tier='pro')
    Profile.objects.filter(subscription_tier='premium_ai').update(subscription_tier='pro')
    Profile.objects.filter(subscription_tier='professional').update(subscription_tier='business')

    Subscription = apps.get_model('expenses', 'Subscription')
    Subscription.objects.filter(plan='premium').update(plan='pro')
    Subscription.objects.filter(plan='premium_ai').update(plan='pro')
    Subscription.objects.filter(plan='professional').update(plan='business')

    SubscriptionPayment = apps.get_model('expenses', 'SubscriptionPayment')
    SubscriptionPayment.objects.filter(plan='premium').update(plan='pro')
    SubscriptionPayment.objects.filter(plan='premium_ai').update(plan='pro')
    SubscriptionPayment.objects.filter(plan='professional').update(plan='business')


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_blogpost_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registration', 'User Registration'), ('user_login', 'User Login'), ('failed_login', 'Failed Login'), ('password_reset', 'Password Reset'), ('expense_creation', 'Expense Creation'), ('expense_deletion', 'Expense Deletion'), ('budget_change', 'Budget Change'), ('support_ticket', 'Support Ticket'), ('payment', 'Payment'), ('subscription_upgrade', 'Subscription Upgrade'), ('team_invite', 'Team Invite'), ('marketplace_order', 'Marketplace Order'), ('forum_report', 'Forum Report')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(migrate_existing_tiers),
        migrations.AlterField(
            model_name='profile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='expenses.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
